services:
  # 1. The Local State (Database)
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-Subscriptions}
      POSTGRES_USER: ${DB_USER:-MailAdmin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mail_net
    logging:
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"
        tag: "docker-mailsub-{{.Name}}"

  # 2. The Message Broker & Cache
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mail_net
    logging:
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"
        tag: "docker-mailsub-{{.Name}}"

  # 3. The API Gateway (Web Server)
  web:
    build:
      context: .
      args:
        PG_MAJOR: ${PG_MAJOR:-15}
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME:-Subscriptions}
      - DB_USER=${DB_USER:-MailAdmin}
      - DB_PASSWORD=${DB_PASSWORD:-password}

      - LDAP_URI=${LDAP_URI:-ldap://localhost:389}
      - LDAP_BIND_DN=${LDAP_BIND_DN:-uid=mailtest,ou=people,dc=csie,dc=ntu,dc=edu,dc=tw}
      - LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD:-}
      - SMTP_HOST=${SMTP_HOST:-localhost}
      - SMTP_PORT=${SMTP_PORT:-25}
      - ALERT_EMAIL_SENDER=${ALERT_EMAIL_SENDER:-mailsub-alert@csie.ntu.edu.tw}
    env_file:
      - .env
      - .env.role
    depends_on:
      - postgres
      - redis
    networks:
      - mail_net
    logging:
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"
        tag: "docker-mailsub-{{.Name}}"

  # 4. The Background Worker (Django-Q)
  worker:
    build:
      context: .
      args:
        PG_MAJOR: ${PG_MAJOR:-15}
    restart: always
    command: python manage.py qcluster
    volumes:
      - .:/app
      - ${LAST_SYNC_DIR:-/var/lib/mailsub}:${LAST_SYNC_DIR:-/var/lib/mailsub}
    environment:
      - DB_NAME=${DB_NAME:-Subscriptions}
      - DB_USER=${DB_USER:-MailAdmin}
      - DB_PASSWORD=${DB_PASSWORD:-password}

      - LDAP_URI=${LDAP_URI:-ldap://localhost:389}
      - LDAP_BIND_DN=${LDAP_BIND_DN:-uid=mailtest,ou=people,dc=csie,dc=ntu,dc=edu,dc=tw}
      - LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD:-}
      - SMTP_HOST=${SMTP_HOST:-localhost}
      - SMTP_PORT=${SMTP_PORT:-25}
      - ALERT_EMAIL_SENDER=${ALERT_EMAIL_SENDER:-mailsub-alert@csie.ntu.edu.tw}
    env_file:
      - .env
      - .env.role
    depends_on:
      - postgres
      - redis
    networks:
      - mail_net
    logging:
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"
        tag: "docker-mailsub-{{.Name}}"

  #frontend interface (React)
  frontend:
      build: 
        context: ./frontend
        dockerfile: Dockerfile
      command: npm run dev -- --host 0.0.0.0 #force listen to docker network traffic
      volumes:
        - ./frontend:/app
        - /app/node_modules
      ports:
        - "${VITE_PORT:-55111}:${VITE_PORT:-55111}"
      environment:
        # This is the magic link between the containers
        - VITE_API_TARGET=${VITE_API_TARGET:-http://web:8000}
        - VITE_PORT=${VITE_PORT:-55111}
      networks:
        - mail_net
      depends_on:
        - web
      logging:
        driver: syslog
        options:
          syslog-address: "unixgram:///dev/log"
          tag: "docker-mailsub-{{.Name}}"

volumes:
  postgres_data:
  redis_data:

networks:
  mail_net:
    driver: bridge
    ipam:
      driver: default
      config:
        # Force Docker to use the 10.5.x.x range instead of 172.16.x.x
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
