# Generated by Django 5.2.13 on 2026-04-10 12:57

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('alias_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Alias name can only contain letters, numbers, and hyphens.', regex='^[a-zA-Z0-9-]+$')])),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('user_id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
            ],
            options={
                'db_table': 'alias',
            },
        ),
        migrations.CreateModel(
            name='AliasTaskQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Alias name can only contain letters, numbers, and hyphens.', regex='^[a-zA-Z0-9-]+$')])),
                ('action', models.CharField(choices=[('add', 'Add Alias'), ('remove', 'Remove Alias')], max_length=10)),
            ],
            options={
                'db_table': 'alias_task_queue',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserTaskQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Alias name can only contain letters, numbers, and hyphens.', regex='^[a-zA-Z0-9-]+$')])),
                ('user_uid', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('add', 'Add Users'), ('remove', 'Remove Users')], max_length=10)),
            ],
            options={
                'db_table': 'user_task_queue',
                'ordering': ['id'],
            },
        ),
    ]
